### ISSUE TITLE
Add Scotty Window Processor to https://flink-packages.org/

### ISSUE THREAD

**Issue by powibol** [TU-Berlin-DIMA/scotty-window-processor#22]
The Flink Community has launched the new platform https://flink-packages.org/ to share community packages. The Scotty Window Processor would be a nice fit to be posted on this platform.

For more information also see the blog post from Ververica: https://www.ververica.com/blog/announcing-flink-community-packages

**Comment by julianev** [comment]
Scotty has now been added as a package to the platform at the following link: https://flink-packages.org/packages/scotty-framework
