### ISSUE TITLE
Questions regarding to  window states and out-of-order late tuples

### ISSUE THREAD

**Issue by tuterbatuhan** [TU-Berlin-DIMA/scotty-window-processor#9]
Hi, 
I have been working on Scotty for a while and it is improving my topologies extremely. 
Yet, I have confronted some issues while I'm processing out-of-order (o-o-o) late tuples. 
I will be happy if you can guide about the following two points.

1) When an o-o-o tuple arrives after which belongs to an ended window, I cannot see the new output of the updated window state. Is there a mechanism that handles these late tuples in Scotty?

2) I couldn't find how Scotty handles the states of the outputted windows. Is there a mechanism to remove the sates once they are no longer needed?

Thank you in advance.

**Comment by PhilippGrulich** [comment]
Hi @tuterbatuhan,
thanks for opening the issue.
I think it would be good to clarify that Scotty is currently handling out-of-order tuples correctly, but does not support refinements (https://www.oreilly.com/ideas/the-world-beyond-batch-streaming-102).
Also, Scotty removes Slices from memory if they are no longer needed.
https://github.com/TU-Berlin-DIMA/scotty-window-processor/blob/41d934585156c20f2ba7ca58b1ced116e78e784d/slicing/src/main/java/de/tub/dima/scotty/slicing/WindowManager.java#L81
It would be very valuable to implement refinements, and I think that it would probably only require slight changes to the Window Manager.

Best,
Philipp

**Comment by tuterbatuhan** [comment]
Thank you for the feedback. 
I have found that I was using V.02 for WindowManager, which does not implement the provided function. 
I will further test my topology.

**Comment by tuterbatuhan** [comment]
If I understand correctly, this cleaning does not happen directly but after a time period. 
 
- I define one tumbling window with 5 seconds size. 
- After the first window [0-5] is output, I send a late tuple with timestamp 4. 
- This late tuple updates the [0-5] slice, whereas that slice should be dropped since there is no other window utilizing it.

**Comment by tuterbatuhan** [comment]
Hi
I have investigated this clearAfterWatermark method 
https://github.com/TU-Berlin-DIMA/scotty-window-processor/blob/41d934585156c20f2ba7ca58b1ced116e78e784d/slicing/src/main/java/de/tub/dima/scotty/slicing/WindowManager.java#L81-L91

If I am not mistaken, the slices are removed from the state when they are older than the maxDelay and it is equal to the window with the maximum size. 

Please consider the following example:
- I have 1 sliding window with size 5 second and sliding period 1 second and current event-time is 6001ms.
- maxDelay = 5000ms 
- removeFromTimestamp = 6001 - 5000 = 1001, which will remove the first slice: 0-1000.
- After this, in event-time 6002, if I receive an out-of-order tuple with the lateness of 6 seconds, with timestamp 0002, it will be discarded since the slice is removed from the state.
- It is also important to keep in mind that the panes 0-5000 and 1000-6000 are already output.

This maxDelay can be parameterized to user-given allowed lateness rather than the maximum window size, to be able to keep the states in memory for the desired allowed lateness. I believe this will partially implement the refinements but still, panes were output before needs to be output again after receiving an out-of-order tuple.

Please correct me if I am missing a concept.
Thank you.

**Comment by PhilippGrulich** [comment]
Hi,

yes this is right.

Best,
Philipp
